name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v2

      - run: choco install -y dotnetfx

      - run: nuget restore Joydance.sln

      - name: Build
        run: msbuild Joydance.sln /p:Configuration=Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Joydance
          path: Joydance/bin/Release/Joydance.exe
