name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Create PyInstaller spec file
        run: pyi-makespec --onefile dance.py

      - name: Edit PyInstaller spec file to include static folder
        shell: pwsh
        run: |
          $specFile = Get-Content dance.spec
          $specFile = $specFile -replace "datas=\[\]", "datas=[('static', 'static')]"
          $specFile | Set-Content dance.spec

      - run: cat dance.spec

      - name: Build executable
        run: pyinstaller dance.spec

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Joydance
          path: dist/dance.exe
